name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # cada 10 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app using wget
        run: |
          echo "Pinging Streamlit app with wget..."
          wget --quiet --tries=3 --timeout=20 \
               --user-agent="Mozilla/5.0 (compatible; GitHubActionBot/1.0)" \
               --no-cache \
               https://luiscaballeroramos.streamlit.app/?embed=true \
               -O /dev/null
