name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # Ejecuta cada 10 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request to Streamlit app
        run: |
          echo "Pinging Streamlit app..."
          curl -L --silent --show-error https://luiscaballeroramos.streamlit.app/ > /dev/null
